### PR TITLE
Added-solution-for-spiralprint

### PR DESCRIPTION
**Pull request by trivediavinash**

### CODE REVIEW

**Comment by trivediavinash** [comment]
@Harshita-Kanal  Hey Please review my PR

**Comment by Harshita-Kanal** [comment]
Would be great if you add the short problem statement as a comment in the code

**Comment by trivediavinash** [comment]
@Harshita-Kanal Yep i  already added the comments and i am sure it is easy to understand as variables name are well defined .

**Comment by trivediavinash** [comment]
@Harshita-Kanal Added the short problem statement as a comment in the code

**Comment by Harshita-Kanal** [comment]
LGTM!

**Pull request merged**
